### ISSUE TITLE
update broken links for screencasts

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/SMBE2024Workshop#12]
and add notes about content being slightly different (since they were for the 2023 workshop)

**Comment by khiron** [comment]
note @gavin this data was stored in the repo for the wiki which is different than the workshop repo.  If you look to the right of the wiki there will be a link to clone the wiki locally 

![image](https://github.com/cogent3/SMBE2024Workshop/assets/1835007/388109ed-f11f-4488-b24e-809e0afffa4c)

I used this method to store the screenshots and screencasts rather than embedding them in issues so the files would be centralized with the content.

**Comment by khiron** [comment]
all links fixed
